FROM jenkins/agent:latest

USER root
RUN apt update \
    && apt install -y chromium \
    chromium-driver

# set display port to avoid crash
ENV DISPLAY=:99

# Install required packages
RUN apt install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-setuptools

USER jenkins